// Curated skill-adjacency graph: pairs of skill ids that are commonly found
// together, with a strength (0-1) used by the staffing-recommendation query
// to widen candidate matches beyond an exact skill match.
export const relatedSkills = [
  ['skill-javascript', 'skill-typescript', 0.9],
  ['skill-javascript', 'skill-react', 0.8],
  ['skill-javascript', 'skill-nodejs', 0.85],
  ['skill-typescript', 'skill-react', 0.7],
  ['skill-typescript', 'skill-angular', 0.7],
  ['skill-react', 'skill-nextjs', 0.85],
  ['skill-react', 'skill-graphql', 0.6],
  ['skill-react', 'skill-accessibility', 0.5],
  ['skill-nodejs', 'skill-express', 0.9],
  ['skill-nodejs', 'skill-mongodb', 0.6],
  ['skill-nodejs', 'skill-graphql', 0.6],
  ['skill-python', 'skill-django', 0.85],
  ['skill-python', 'skill-ml', 0.7],
  ['skill-python', 'skill-nlp', 0.65],
  ['skill-python', 'skill-dataviz', 0.6],
  ['skill-ml', 'skill-nlp', 0.8],
  ['skill-ml', 'skill-dataviz', 0.5],
  ['skill-go', 'skill-kubernetes', 0.6],
  ['skill-docker', 'skill-kubernetes', 0.9],
  ['skill-kubernetes', 'skill-terraform', 0.6],
  ['skill-terraform', 'skill-aws', 0.7],
  ['skill-terraform', 'skill-azure', 0.65],
  ['skill-terraform', 'skill-gcp', 0.65],
  ['skill-aws', 'skill-serverless', 0.75],
  ['skill-aws', 'skill-cicd', 0.6],
  ['skill-aws', 'skill-cybersecurity', 0.5],
  ['skill-azure', 'skill-dotnet-core', 0.7],
  ['skill-java', 'skill-spring-boot', 0.9],
  ['skill-spring-boot', 'skill-postgresql', 0.5],
  ['skill-csharp', 'skill-dotnet-core', 0.9],
  ['skill-postgresql', 'skill-data-modeling', 0.7],
  ['skill-mongodb', 'skill-data-modeling', 0.6],
  ['skill-neo4j', 'skill-data-modeling', 0.75],
  ['skill-kafka', 'skill-etl', 0.7],
  ['skill-etl', 'skill-data-modeling', 0.65],
  ['skill-redis', 'skill-nodejs', 0.5],
  ['skill-elasticsearch', 'skill-dataviz', 0.5],
  ['skill-cicd', 'skill-docker', 0.7],
  ['skill-rust', 'skill-go', 0.4],
  ['skill-project-mgmt', 'skill-agile', 0.8],
  ['skill-project-mgmt', 'skill-stakeholder-comms', 0.75],
  ['skill-stakeholder-comms', 'skill-client-presentations', 0.8],
  ['skill-mentoring', 'skill-tech-writing', 0.5],
  ['skill-fintech', 'skill-cybersecurity', 0.5],
  ['skill-healthcare', 'skill-data-modeling', 0.4],
  ['skill-ecommerce', 'skill-dataviz', 0.4],
  ['skill-supply-chain', 'skill-data-modeling', 0.4],
  ['skill-edtech', 'skill-stakeholder-comms', 0.3],
];
