// Curated, realistic skill catalog -- not randomly generated, since skill names
// and categories are the backbone of the RELATED_TO adjacency graph below.
export const skills = [
  // Languages
  { id: 'skill-javascript', name: 'JavaScript', category: 'Language' },
  { id: 'skill-typescript', name: 'TypeScript', category: 'Language' },
  { id: 'skill-python', name: 'Python', category: 'Language' },
  { id: 'skill-go', name: 'Go', category: 'Language' },
  { id: 'skill-java', name: 'Java', category: 'Language' },
  { id: 'skill-csharp', name: 'C#', category: 'Language' },
  { id: 'skill-rust', name: 'Rust', category: 'Language' },
  { id: 'skill-ruby', name: 'Ruby', category: 'Language' },
  // Frameworks
  { id: 'skill-react', name: 'React', category: 'Framework' },
  { id: 'skill-vue', name: 'Vue', category: 'Framework' },
  { id: 'skill-angular', name: 'Angular', category: 'Framework' },
  { id: 'skill-nodejs', name: 'Node.js', category: 'Framework' },
  { id: 'skill-express', name: 'Express', category: 'Framework' },
  { id: 'skill-django', name: 'Django', category: 'Framework' },
  { id: 'skill-spring-boot', name: 'Spring Boot', category: 'Framework' },
  { id: 'skill-dotnet-core', name: '.NET Core', category: 'Framework' },
  { id: 'skill-nextjs', name: 'Next.js', category: 'Framework' },
  { id: 'skill-graphql', name: 'GraphQL', category: 'Framework' },
  // Cloud & infra
  { id: 'skill-aws', name: 'AWS', category: 'Cloud' },
  { id: 'skill-azure', name: 'Azure', category: 'Cloud' },
  { id: 'skill-gcp', name: 'GCP', category: 'Cloud' },
  { id: 'skill-terraform', name: 'Terraform', category: 'Cloud' },
  { id: 'skill-kubernetes', name: 'Kubernetes', category: 'Cloud' },
  { id: 'skill-docker', name: 'Docker', category: 'Cloud' },
  { id: 'skill-cicd', name: 'CI/CD', category: 'Cloud' },
  { id: 'skill-serverless', name: 'Serverless', category: 'Cloud' },
  // Data
  { id: 'skill-postgresql', name: 'PostgreSQL', category: 'Data' },
  { id: 'skill-mongodb', name: 'MongoDB', category: 'Data' },
  { id: 'skill-neo4j', name: 'Neo4j/Cypher', category: 'Data' },
  { id: 'skill-redis', name: 'Redis', category: 'Data' },
  { id: 'skill-kafka', name: 'Kafka', category: 'Data' },
  { id: 'skill-data-modeling', name: 'Data Modeling', category: 'Data' },
  { id: 'skill-etl', name: 'ETL Pipelines', category: 'Data' },
  { id: 'skill-ml', name: 'Machine Learning', category: 'Data' },
  { id: 'skill-nlp', name: 'NLP', category: 'Data' },
  { id: 'skill-dataviz', name: 'Data Visualization', category: 'Data' },
  { id: 'skill-elasticsearch', name: 'Elasticsearch', category: 'Data' },
  // Soft skills
  { id: 'skill-stakeholder-comms', name: 'Stakeholder Communication', category: 'Soft Skill' },
  { id: 'skill-project-mgmt', name: 'Project Management', category: 'Soft Skill' },
  { id: 'skill-tech-writing', name: 'Technical Writing', category: 'Soft Skill' },
  { id: 'skill-mentoring', name: 'Mentoring', category: 'Soft Skill' },
  { id: 'skill-agile', name: 'Agile Facilitation', category: 'Soft Skill' },
  { id: 'skill-client-presentations', name: 'Client Presentations', category: 'Soft Skill' },
  // Domain
  { id: 'skill-fintech', name: 'Fintech', category: 'Domain' },
  { id: 'skill-healthcare', name: 'Healthcare Compliance', category: 'Domain' },
  { id: 'skill-ecommerce', name: 'E-commerce', category: 'Domain' },
  { id: 'skill-cybersecurity', name: 'Cybersecurity', category: 'Domain' },
  { id: 'skill-supply-chain', name: 'Supply Chain', category: 'Domain' },
  { id: 'skill-edtech', name: 'EdTech', category: 'Domain' },
  { id: 'skill-accessibility', name: 'Accessibility', category: 'Domain' },
];
